groups:
  - name: system_alerts
    rules:
      - alert: LowDiskSpace
        expr: (node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 15 and ON (instance, device, mountpoint) node_filesystem_readonly == 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Host out of disk space (instance {{ $labels.instance }})
          description: Disk is almost full (< 15% left)\n  VALUE = {{ $value }}

      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: Host high CPU load (instance {{ $labels.instance }})
          description: CPU load is > 80%\n  VALUE = {{ $value }}

      - alert: TargetDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Target {{ $labels.job }}  is unavailable
          description: Target {{ $labels.job }} is unavailable on {{ $labels.instance }}

      - alert: ContainerDown
        expr:  time() - last_over_time(container_last_seen{name!=""}[10m]) > 60
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Container {{ $labels.name }} is unavailable
          description: Container  {{ $labels.name }} has not been seen for more than 1 minute

